# Generated by Django 5.1.7 on 2025-03-26 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BlogArticle",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "title",
                    models.CharField(help_text="Введите заголовок записи", max_length=100, verbose_name="Заголовок"),
                ),
                ("content", models.TextField(help_text="Введите текст записи", verbose_name="Содержимое")),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        help_text="Загрузите изображение для превью",
                        null=True,
                        upload_to="preview/",
                        verbose_name="Изображение",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")),
                ("is_publication", models.BooleanField(default=True, verbose_name="Признак публикации")),
                ("count_view", models.IntegerField(verbose_name="Количество просмотров")),
            ],
            options={
                "verbose_name": "статья",
                "verbose_name_plural": "статьи",
                "ordering": ["title"],
            },
        ),
    ]
