# Generated by Django 5.1.7 on 2025-03-26 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blogarticle",
            options={
                "ordering": ["title", "created_at", "views_counter"],
                "verbose_name": "статья",
                "verbose_name_plural": "статьи",
            },
        ),
        migrations.RenameField(
            model_name="blogarticle",
            old_name="photo",
            new_name="preview",
        ),
        migrations.RemoveField(
            model_name="blogarticle",
            name="count_view",
        ),
        migrations.AddField(
            model_name="blogarticle",
            name="views_counter",
            field=models.PositiveIntegerField(
                default=0, help_text="Укажите количество просмотров", verbose_name="Количество просмотров"
            ),
        ),
    ]
