# Generated by Django 4.2.2 on 2025-04-07 10:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("blog", "0002_alter_blogarticle_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogarticle",
            name="author",
            field=models.ForeignKey(
                blank=True,
                help_text="Укажите автора статьи",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="articles",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор",
            ),
        ),
    ]
