# Generated by Django 5.1.7 on 2025-03-13 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(
                help_text="Введите название категории", max_length=50, unique=True, verbose_name="Наименование"
            ),
        ),
    ]
