# Generated by Django 5.1.7 on 2025-03-14 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_alter_category_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="updated_at",
            field=models.DateField(auto_now=True, verbose_name="Дата последнего изменения"),
        ),
    ]
