# Generated by Django 5.1.7 on 2025-03-26 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_remove_product_photo_product_preview"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="preview",
            new_name="photo",
        ),
    ]
